name: auctionhair
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^0.13.5
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  intl: ^0.19.0
  video_player: ^2.8.5
  flutter_html: ^3.0.0-beta.2
  cached_network_image: ^3.3.0
  cached_network_image_platform_interface: ^3.0.0
  camera: ^0.11.1
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  permission_handler: ^11.4.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_svg: ^2.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/bank_icons/
    - assets/lots/auctions/

dependency_overrides:
  win32: ^5.5.4